name: Push changes
description: Push changes
inputs:
  branch:
    description: Branch name
    required: true
  pull-before-push:
    description: "Allowed values: true | false | undefined"
    required: false
  force:
    description: "Allowed values: true | false | undefined"
    required: false
  
runs:
  using: "composite"
  steps:
    - name: Push changes
      shell: bash
      run: |
        IS_BRANCH_EXISTS=$(git ls-remote --heads origin "${{ inputs.branch }}" | grep -q "refs/heads/${{ inputs.branch }}" && echo true || echo false)
        if [[ "$IS_BRANCH_EXISTS" == "true" ]]; then
          if [[ "${{ inputs.force }}" == "true" ]]; then
            if [[ "${{ inputs.pull-before-push }}" == "true" ]]; then
              git pull origin "${{ inputs.branch }}" 
            fi
            git push --force origin "${{ inputs.branch }}"
          else
            if [[ "${{ inputs.pull-before-push }}" == "true" ]]; then
              git pull origin "${{ inputs.branch }}"
            fi
            git push origin "${{ inputs.branch }}"
          fi
        else
          if [[ "${{ inputs.pull-before-push }}" == "true" ]]; then
            git pull origin "${{ inputs.branch }}"
          fi
          git push --set-upstream origin "${{ inputs.branch }}"
        fi

