name: Commit changes
description: Commit changes
inputs:
  message:
    description: Commit message
    required: true

runs:
  using: "composite"
  steps:
    - name: setup
      shell: bash
      run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
    - name: Commit changes
      shell: bash
      run: |
        git add --all .
        git commit -m "${{ inputs.message }}"

