inputs:
  configuration:
    description: 'Allowed value: Release | Debug'
    type: string
    default: Debug
    required: true
runs:
  using: "composite"
  steps:
    setup:
      name: Setup project
      runs-on: ubuntu-latest
      steps:
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            8.0.x
            7.0.x
            6.0.x
  