name: Release
description: Releases selected project
inputs:
  GITHUB_TOKEN:
    description: 'GITHUB_TOKEN'
    required: true
  NUGET_API_KEY:
    description: 'NUGET_API_KEY'
    required: true
  project:
    required: true
    description: "Allowed values: EncryptedConfigValue.Module | EncryptedConfigValue.AspNetCore"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/setup-dotnet-action

    - name: Build
      shell: bash
      run: dotnet build ./EncryptedConfigValue.sln --configuration Release

    - name: Pack
      shell: bash
      run: dotnet pack ./${{ inputs.project }}/ --configuration Release

    - name: Push NuGet package
      shell: bash
      run: |
        version=$(sed -n 's:.*<version>\(.*\)</version>.*:\1:p' ./${{ inputs.project }}/${{ inputs.project }}.nuspec)
        echo "dotnet nuget push ./${{ inputs.project }}/bin/Release/${{ inputs.project }}.$version.nupkg"
        # dotnet nuget push "./${{ inputs.project }}/bin/Release/${{ inputs.project }}.$version.nupkg" --api-key ${{ inputs.NUGET_API_KEY }} -src https://api.nuget.org/v3/index.json
