name: Has Changes
description: Checks if project has any changes since last release
inputs:
  project:
    required: true
    description: "Allowed values: EncryptedConfigValue.Module | EncryptedConfigValue.AspNetCore"
outputs:
  result:
    description: "true | false"
    value: "${{ steps.validate.outputs.result }}"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Validate
      shell: bash
      id: validate
      run: |
        hash_current_main=$(git rev-parse origin/main)
        if [ -z "$hash_current_main" ]; then
          echo "Cannot fetch hash of origin/main"
          exit 1
        fi
        
        hash_of_last_release=$(git tag -l "${{ inputs.project }}/*" | sort -V | tail -n 1 | xargs -I {} git rev-list -n 1 {})
        if [ -z "$hash_of_last_release" ]; then
          echo "Cannot fetch hash of last release"
          exit 1
        fi

        has_differences=$(git diff --quiet "$hash_current_main:./${{ inputs.project }}" "$hash_of_last_release:./${{ inputs.project }}" -- ':!*.nuspec' && echo false || echo true)
        echo "result=$has_differences" >> $GITHUB_OUTPUT
