on:
  workflow_call:
    inputs:
      build:
        description: 'Build before test'
        type: boolean
        default: true
jobs:
  test:
    name: Test on ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-latest ]
    steps:
    - uses: ./.github/workflows/action-setup-dotnet.yml

    - name: Build
      if: ${{ inputs.build }}
      run: dotnet build ./EncryptedConfigValue.sln --configuration Debug

    - name: Test
      run: dotnet test --no-restore --verbosity normal
