on: []
jobs:
  test:
    name: test-${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-latest ]
    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: | 
          8.0.x
          7.0.x
          6.0.x 
    - name: Build
      run: dotnet build ./EncryptedConfigValue.sln --configuration Release
    - name: Test
      run: dotnet test --no-restore --verbosity normal
