name: Release

on:
  workflow_dispatch:
  pull_request:
    types: 
      - closed
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      PULL_REQUEST_MERGED: ${{ github.event.pull_request.merged }}
    outputs:
      module: ${{ steps.validate.outputs.result }}
    steps:
      - uses: actions/checkout@v4

      - name: Validate
        id: validate
        run: |
          merged="$([[ "$PULL_REQUEST_MERGED" == "true" ]] && echo true || echo false)"
          originated_from_release_pr="$([[ "$GITHUB_HEAD_REF" =~ ^bot\/[^\/]+\/update-nuspec$ ]] && echo true || echo false)"
          result="$([[ "$merged" == true && "$originated_from_release_pr" == true ]] && echo true || echo false)"
          echo "result=$result" >> $GITHUB_OUTPUT

  setup:
    needs: [validate]
    if: needs.validate.outputs.module == 'true'
    runs-on: ubuntu-latest
    outputs:
      project: ${{ steps.setup.outputs.project }}
      
    steps:
      - name: Setup
        id: setup
        run: |
          project=$(echo "$GITHUB_HEAD_REF" | sed 's#bot/\(.*\)/update-nuspec#\1#')
          echo "project=$project" >> $GITHUB_OUTPUT

  release:
    needs: [setup]
    if: needs.setup.outputs.project == 'EncryptedConfigValue.Module' || needs.setup.outputs.project == 'EncryptedConfigValue.AspNetCore'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/release-action
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          project: ${{ needs.setup.outputs.project }}

  tag:
    needs: [setup, release]
    if: needs.setup.outputs.project == 'EncryptedConfigValue.Module' || needs.setup.outputs.project == 'EncryptedConfigValue.AspNetCore'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      
      - name: Setup git
        shell: bash
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Tag
        shell: bash
        run: |
          project="${{ needs.setup.outputs.project }}"
          version=$(sed -n 's:.*<version>\(.*\)</version>.*:\1:p' ./$project/$project.nuspec)
          hash=$(sed -n 's:.*commit="\([^"]*\)".*:\1:p' ./$project/$project.nuspec)
          git tag -a "$project/$version" -m "$project v$version" $hash
          git push origin tag "$project/$version"
        env:
          GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}