name: Update dotnet version

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * MON'

concurrency:
  group: update-dotnet-version
  cancel-in-progress: true

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      active-dotnet-version: ${{ steps.active-dotnet-version.outputs.value }}
      branch: ${{ steps.set-branch-name.outputs.value }}
    steps:
      - uses: actions/checkout@v4
      - name: Set branch name
        id: set-branch-name
        run: |
          echo "value=bot/update-dotnet-version" >> $GITHUB_OUTPUT
      - name: Get active .NET versions
        id: active-dotnet-version
        shell: pwsh
        run: |
          $activeVersions = ((((Invoke-WebRequest -Uri "https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json" -UseBasicParsing | ConvertFrom-Json)."releases-index" | Where-Object { $_."product" -eq ".NET" -and $_."support-phase" -eq "active" | Sort-Object -Property channel-version -Descending } | Select -Property channel-version)."channel-version") -split "," | ForEach-Object { "net$_" }) -join ","
          if ([string]::IsNullOrWhitespace($activeVersions)) {
            exit 1
          }
          "value=$($activeVersions)" >> $env:GITHUB_OUTPUT
          exit 0
      - name: "Reset branches"
        run: |
           BRANCHES=(
             "${{ steps.set-branch-name.outputs.value }}",
             "${{ steps.set-branch-name.outputs.value }}/partial/EncryptedConfigValue.Module"
             "${{ steps.set-branch-name.outputs.value }}/partial/EncryptedConfigValue.AspNetCore"
             "${{ steps.set-branch-name.outputs.value }}/partial/EncryptedConfigValue.Cli"
             "${{ steps.set-branch-name.outputs.value }}/partial/pipelines"
           )
           for BRANCH in "${BRANCHES[@]}"; do
             is_branch_exists_origin=$(git ls-remote --heads origin $BRANCH | grep -q "refs/heads/$BRANCH" && echo true || echo false)
             if [[ "$is_branch_exists_origin" == "true" ]]; then
               git push origin --delete $BRANCH || { echo "Failed to delete branch $BRANCH on origin."; exit 1; }
             fi
           done

  should-updated-targetframeworks:
    needs: [init]
    runs-on: ubuntu-latest
    outputs:
      module: ${{ steps.finalize.outputs.module }}
      aspnetcore: ${{ steps.finalize.outputs.aspnetcore }}
      cli: ${{ steps.finalize.outputs.cli }}
      
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/can-update-targetframeworks
        id: should-update-targetframeworks-module
        with:
          project: EncryptedConfigValue.Module
          target-dotnet-versions: ${{ needs.init.outputs.active-dotnet-version }}
      - uses: ./.github/actions/can-update-targetframeworks
        id: should-update-targetframeworks-aspnetcore
        with:
          project: EncryptedConfigValue.AspNetCore
          target-dotnet-versions: ${{ needs.init.outputs.active-dotnet-version }}
      - uses: ./.github/actions/can-update-targetframeworks
        id: should-update-targetframeworks-cli
        with:
          project: EncryptedConfigValue.Cli
          target-dotnet-versions: ${{ needs.init.outputs.active-dotnet-version }}

      - name: Finalize
        id: finalize
        run: |
          echo "module=${{ steps.should-update-targetframeworks-module.outputs.result }}" >> $GITHUB_OUTPUT
          echo "aspnetcore=${{ steps.should-update-targetframeworks-aspnetcore.outputs.result }}" >> $GITHUB_OUTPUT
          echo "cli=${{ steps.should-update-targetframeworks-cli.outputs.result }}" >> $GITHUB_OUTPUT

  update-dotnet-module:
    needs: [init, should-updated-targetframeworks]
    if: needs.should-updated-targetframeworks.outputs.module == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      project: ${{ steps.set-project-name.outputs.value }}
      branch: ${{ steps.set-branch-name.outputs.value }}  
    steps:
      - uses: actions/checkout@v4
      - name: Set project name
        id: set-project-name
        run: |
          echo "value=EncryptedConfigValue.Module" >> $GITHUB_OUTPUT
      - name: Set branch name
        id: set-branch-name
        run: |
          echo "value=${{ needs.init.outputs.branch }}/partial/${{ steps.set-project-name.outputs.value }}" >> $GITHUB_OUTPUT
      - uses: ./.github/actions/setup-dotnet
      - uses: ./.github/actions/setup-git
        with:
          branch: ${{ steps.set-branch-name.outputs.value }}
          hard-reset: true
      - uses: ./.github/actions/update-dotnet-version
        with:
          project: ${{ steps.set-project-name.outputs.value }}
          target-dotnet-versions: ${{ needs.init.outputs.active-dotnet-version }}
      - uses: ./.github/actions/commit-changes
        with:
          message: Update .NET version in ${{ steps.set-project-name.outputs.value }}
      - uses: ./.github/actions/push-changes
        with:
          branch: ${{ steps.set-branch-name.outputs.value }}
          force: true

  update-dotnet-aspnetcore:
    needs: [init, should-updated-targetframeworks]
    if: needs.should-updated-targetframeworks.outputs.aspnetcore == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      project: ${{ steps.set-project-name.outputs.value }}
      branch: ${{ steps.set-branch-name.outputs.value }}  
    steps:
      - uses: actions/checkout@v4
      - name: Set project name
        id: set-project-name
        run: |
          echo "value=EncryptedConfigValue.AspNetCore" >> $GITHUB_OUTPUT
      - name: Set branch name
        id: set-branch-name
        run: |
          echo "value=${{ needs.init.outputs.branch }}/partial/${{ steps.set-project-name.outputs.value }}" >> $GITHUB_OUTPUT
      - uses: ./.github/actions/setup-dotnet
      - uses: ./.github/actions/setup-git
        with:
          branch: ${{ steps.set-branch-name.outputs.value }}
          hard-reset: true
      - uses: ./.github/actions/update-dotnet-version
        with:
          project: ${{ steps.set-project-name.outputs.value }}
          target-dotnet-versions: ${{ needs.init.outputs.active-dotnet-version }}
      - uses: ./.github/actions/commit-changes
        with:
          message: Update .NET version in ${{ steps.set-project-name.outputs.value }}
      - uses: ./.github/actions/push-changes
        with:
          branch: ${{ steps.set-branch-name.outputs.value }}
          force: true

  update-dotnet-cli:
    needs: [init, should-updated-targetframeworks]
    if: needs.should-updated-targetframeworks.outputs.cli == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      project: ${{ steps.set-project-name.outputs.value }}
      branch: ${{ steps.set-branch-name.outputs.value }}  
    steps:
      - uses: actions/checkout@v4
      - name: Set project name
        id: set-project-name
        run: |
          echo "value=EncryptedConfigValue.Cli" >> $GITHUB_OUTPUT
      - name: Set branch name
        id: set-branch-name
        run: |
          echo "value=${{ needs.init.outputs.branch }}/partial/${{ steps.set-project-name.outputs.value }}" >> $GITHUB_OUTPUT
      - uses: ./.github/actions/setup-dotnet
      - uses: ./.github/actions/setup-git
        with:
          branch: ${{ steps.set-branch-name.outputs.value }}
          hard-reset: true
      - uses: ./.github/actions/update-dotnet-version
        with:
          project: ${{ steps.set-project-name.outputs.value }}
          target-dotnet-versions: ${{ needs.init.outputs.active-dotnet-version }}
      - uses: ./.github/actions/commit-changes
        with:
          message: Update .NET version in ${{ steps.set-project-name.outputs.value }}
      - uses: ./.github/actions/push-changes
        with:
          branch: ${{ steps.set-branch-name.outputs.value }}
          force: true

  update-pipelines:
    needs: [init, should-updated-targetframeworks]
    if: needs.should-updated-targetframeworks.outputs.module == 'true' || needs.should-updated-targetframeworks.outputs.aspnetcore == 'true' ||  needs.should-updated-targetframeworks.outputs.cli == 'true'
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.set-branch-name.outputs.value }}  
    steps:
      - uses: actions/checkout@v4
      - name: Set branch name
        id: set-branch-name
        run: |
          echo "value=${{ needs.init.outputs.branch }}/partial/pipelines" >> $GITHUB_OUTPUT
      - uses: ./.github/actions/setup-git
        with:
          branch: ${{ steps.set-branch-name.outputs.value }}
          hard-reset: true
      - name: Update setup-dotnet action
        shell: pwsh
        run: |
          $versionString = "${{ needs.init.outputs.active-dotnet-version }}"
          write-host $versionString
          $filePath = "./.github/actions/setup-dotnet/action.yml"
          $versions = $versionString -split ',' | ForEach-Object { ($_ -replace 'net', '') + ".x" }
          $yamlContent = Get-Content $filePath -Raw
          $dotnetVersionPattern = "(?sm)dotnet-version:\s*\|.*?(?=\w+:|\z)"
          $indentation = if ($yamlContent -match "([ \t]*)dotnet-version: \|") { "$($matches[1])  " } else { "" }
          $newDotnetVersionSection = "dotnet-version: |`r`n${indentation}" + ($versions | ForEach-Object { "${indentation}$_" } | Out-String).Trim()
          $updatedYamlContent = $yamlContent -replace $dotnetVersionPattern, $newDotnetVersionSection
          Set-Content $filePath -Value $updatedYamlContent
      - uses: ./.github/actions/commit-changes
        with:
          message: Update pipelines
      - uses: ./.github/actions/push-changes
        with:
          branch: ${{ steps.set-branch-name.outputs.value }}
          force: true

  has-changes-module:
    needs: [update-dotnet-module]
    runs-on: ubuntu-latest
    outputs:
      project: ${{ steps.set-project-name.outputs.value }}
      result: ${{ steps.finalize.outputs.result }}
    steps:
      - uses: actions/checkout@v4
      - name: Set project name
        id: set-project-name
        run: |
          echo "value=EncryptedConfigValue.Module" >> $GITHUB_OUTPUT
      - uses: ./.github/actions/has-changes
        id: has-changes
        with:
          project: ${{ steps.set-project-name.outputs.value }}
      - name: Finalize
        id: finalize
        run: |
          echo "result=${{ steps.has-changes.outputs.result }}" >> $GITHUB_OUTPUT

  has-changes-aspnetcore:
    needs: [update-dotnet-aspnetcore]
    runs-on: ubuntu-latest
    outputs:
      project: ${{ steps.set-project-name.outputs.value }}
      result: ${{ steps.finalize.outputs.result }}
    steps:
      - uses: actions/checkout@v4
      - name: Set project name
        id: set-project-name
        run: |
          echo "value=EncryptedConfigValue.AspNetCore" >> $GITHUB_OUTPUT
      - uses: ./.github/actions/has-changes
        id: has-changes
        with:
          project: ${{ steps.set-project-name.outputs.value }}
      - name: Finalize
        id: finalize
        run: |
          echo "result=${{ steps.has-changes.outputs.result }}" >> $GITHUB_OUTPUT

  has-changes-cli:
    needs: [update-dotnet-cli]
    runs-on: ubuntu-latest
    outputs:
      project: ${{ steps.set-project-name.outputs.value }}
      result: ${{ steps.finalize.outputs.result }}
    steps:
      - uses: actions/checkout@v4
      - name: Set project name
        id: set-project-name
        run: |
          echo "value=EncryptedConfigValue.Cli" >> $GITHUB_OUTPUT
      - uses: ./.github/actions/has-changes
        id: has-changes
        with:
          project: ${{ steps.set-project-name.outputs.value }}
      - name: Finalize
        id: finalize
        run: |
          echo "result=${{ steps.has-changes.outputs.result }}" >> $GITHUB_OUTPUT

  update-nuspec-module:
    needs: [init, has-changes-module]
    if: needs.has-changes-module.outputs.result == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      project: ${{ steps.set-project-name.outputs.value }}
      branch: ${{ steps.set-branch-name.outputs.value }}  
    steps:
      - uses: actions/checkout@v4
      - name: Set project name
        id: set-project-name
        run: |
          echo "value=EncryptedConfigValue.Module" >> $GITHUB_OUTPUT
      - name: Set branch name
        id: set-branch-name
        run: |
          echo "value=${{ needs.init.outputs.branch }}/partial/${{ steps.set-project-name.outputs.value }}" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-git
        with:
          branch: ${{ steps.set-branch-name.outputs.value }}
      - uses: ./.github/actions/update-nuspec-file
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          project: ${{ steps.set-project-name.outputs.value }}
          additional-files: |
            ./Readme.md
      - uses: ./.github/actions/commit-changes
        with:
          message: Update module nuspec
      - uses: ./.github/actions/push-changes
        with:
          branch: ${{ steps.set-branch-name.outputs.value }}

  update-nuspec-aspnetcore:
    needs: [init, has-changes-aspnetcore]
    if: needs.has-changes-aspnetcore.outputs.result == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      project: ${{ steps.set-project-name.outputs.value }}
      branch: ${{ steps.set-branch-name.outputs.value }}  
    steps:
      - uses: actions/checkout@v4
      - name: Set project name
        id: set-project-name
        run: |
          echo "value=EncryptedConfigValue.AspNetCore" >> $GITHUB_OUTPUT
      - name: Set branch name
        id: set-branch-name
        run: |
          echo "value=${{ needs.init.outputs.branch }}/partial/${{ steps.set-project-name.outputs.value }}" >> $GITHUB_OUTPUT
      - uses: ./.github/actions/setup-git
        with:
          branch: ${{ steps.set-branch-name.outputs.value }}
      - uses: ./.github/actions/update-nuspec-file
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          project: ${{ steps.set-project-name.outputs.value }}
          external-dependencies-sources: |
            EncryptedConfigValue
          additional-files: |
            ./Readme.md
      - uses: ./.github/actions/commit-changes
        with:
          message: Update aspnetcore nuspec
      - uses: ./.github/actions/push-changes
        with:
          branch: ${{ steps.set-branch-name.outputs.value }}

  update-nuspec-cli:
    needs: [init, has-changes-cli]
    if: needs.has-changes-cli.outputs.result == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      project: ${{ steps.set-project-name.outputs.value }}
      branch: ${{ steps.set-branch-name.outputs.value }}  
    steps:
      - uses: actions/checkout@v4
      - name: Set project name
        id: set-project-name
        run: |
          echo "value=EncryptedConfigValue.Cli" >> $GITHUB_OUTPUT
      - name: Set branch name
        id: set-branch-name
        run: |
          echo "value=${{ needs.init.outputs.branch }}/partial/${{ steps.set-project-name.outputs.value }}" >> $GITHUB_OUTPUT
      - uses: ./.github/actions/setup-git
        with:
          branch: ${{ steps.set-branch-name.outputs.value }}
      - uses: ./.github/actions/update-nuspec-file
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          project: ${{ steps.set-project-name.outputs.value }}
          external-dependencies-sources: |
            EncryptedConfigValue
          additional-files: |
            ./Readme.md
      - uses: ./.github/actions/commit-changes
        with:
          message: Update cli nuspec
      - uses: ./.github/actions/push-changes
        with:
          branch: ${{ steps.set-branch-name.outputs.value }}

  finalize:
    needs: [
        init,
        should-updated-targetframeworks,
        update-dotnet-module,
        update-dotnet-aspnetcore,
        update-dotnet-cli,
        update-nuspec-module, 
        update-nuspec-aspnetcore, 
        update-nuspec-cli, 
        update-pipelines
    ]
    if: needs.should-updated-targetframeworks.outputs.module == 'true' || needs.should-updated-targetframeworks.outputs.aspnetcore == 'true' ||  needs.should-updated-targetframeworks.outputs.cli == 'true'
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: ./.github/actions/setup-git
          with:
            branch: ${{ needs.init.outputs.branch }}
            hard-reset: true
        - name: Merge
          run:
           TARGET_BRANCH="${{ needs.init.outputs.branch }}"
           PARTIAL_BRANCHES=(
             "${{ needs.init.outputs.branch }}/partial/EncryptedConfigValue.Module"
             "${{ needs.init.outputs.branch }}/partial/EncryptedConfigValue.AspNetCore"
             "${{ needs.init.outputs.branch }}/partial/EncryptedConfigValue.Cli"
             "${{ needs.init.outputs.branch }}/partial/pipelines"
           )
           git checkout $TARGET_BRANCH || exit 1
           for BRANCH in "${PARTIAL_BRANCHES[@]}"; do
             is_branch_exists=$(git ls-remote --heads origin $BRANCH | grep -q "refs/heads/$BRANCH" && echo true || echo false)
             if [[ "$is_branch_exists" == "true" ]]; then           
               echo "Rebasing $BRANCH onto $TARGET_BRANCH..."
               git checkout $BRANCH || exit 1
               git rebase $TARGET_BRANCH || { echo "Rebase failed for $BRANCH. Aborting."; exit 1; }
               echo "Rebase successful for $BRANCH."
             fi
           done
           git checkout $TARGET_BRANCH           
           for BRANCH in "${PARTIAL_BRANCHES[@]}"; do
             is_branch_exists_origin=$(git ls-remote --heads origin $BRANCH | grep -q "refs/heads/$BRANCH" && echo true || echo false)
             if [[ "$is_branch_exists_origin" == "true" ]]; then           
               echo "Deleting branch $BRANCH on origin..."
               git push origin --delete $BRANCH || { echo "Failed to delete branch $BRANCH on origin. Continuing."; }
             fi 
           done
        - uses: ./.github/actions/commit-changes
          with:
            message: Update cli nuspec
        - uses: ./.github/actions/push-changes
          with:
            branch: ${{ needs.init.outputs.branch }}
            force: true
        - uses: ./.github/actions/put-pull-request
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            title: Update .NET versions
            body: This PR updates .NET version used in project and pipelines.
            from: ${{ needs.init.outputs.branch }}
            into: main
