name: Validate pull request
on: 
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
    branches:    
      - 'main'
jobs:
  validate-actors:
    runs-on: ubuntu-latest
    env:
      ALLOWED_ACTORS: ("Hau-Hau")
    steps:
      - name: check actor
        if: ${{ contains(env.ALLOWED_ACTORS, github.actor ) }}        
        run: exit 1
