name: Validate if user can complete release PR
on: 
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
    branches:    
      - 'main'
jobs:
  check-actors:
    runs-on: ubuntu-latest
    steps:
      - name: check actor
        run: |
          originated_from_release_pr="$([[ "$GITHUB_HEAD_REF" =~ ^bot\/[^\/]+\/update-nuspec$ ]] && echo true || echo false)"
          skip_check="$([[ "$originated_from_release_pr" == false ]] && echo true || echo false)"
          if [[ $skip_check == true ]]; then
            exit 0
          fi

          IFS=',' read -r -a username_array <<< "${{ secrets.ACCEPT_RELEASE_PR_ALLOW_LIST }}"
          user_found=false
          for username in "${username_array[@]}"
          do
              if [ "$username" == "${{ github.actor }}" ]; then
                  user_found=true
                  break
              fi
          done
          if [ "$user_found" = false ]; then
              exit 1
          fi



